#cloud-config
ssh_authorized_keys:
  - ${custom_ssh}

runcmd:
  - apt-get update
  - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
# Installs current Docker supported version for RKE cluster
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - passwd ubuntu 
  - echo -e "ubuntu\nubuntu" | passwd ubuntu
  - groupadd docker
  - usermod -aG docker $USER
  - newgrp docker
  - systemctl enable docker
  - chown ubuntu /var/run/docker.sock  
  - chmod 666 /var/run/docker.sock
  - sysctl -w net.bridge.bridge-nf-call-iptables=1  